export CLICOLOR=1
export EDITOR=nvim
export VISUAL=$EDITOR

export PROJECTS="${HOME}/Developer"

export CMAKE_EXPORT_COMPILE_COMMANDS=1

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1

# Disable iTerm's mark rendering.
export ITERM2_SQUELCH_MARK=1

# Ensure brew is loaded into the environment.
eval "$(/opt/homebrew/bin/brew shellenv)"

