export EDITOR=nvim
export VISUAL=$EDITOR

export CMAKE_GENERATOR="Unix Makefiles"
export CMAKE_BUILD_TYPE=Debug
export CMAKE_EXPORT_COMPILE_COMMANDS=ON

path=("${HOME}/.cargo/bin" $path)
path=("${HOME}/.bin" $path)
path=("/opt/homebrew/opt/llvm/bin" $path)
export PATH

# Ensure Brew is in the path.
if [[ -d /opt/homebrew ]]
then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

